import { Equipment, CampusLocation, MaintenanceExecution, EquipmentFrequency } from '../types';

export const INITIAL_BUILDINGS: string[] = [
  'Edificio Administrativo',
  'Bloque Bachillerato',
  'Bloque Primaria',
  'Edificio Central',
  'Edificio Cultural',
  'Edificio de Servicios',
  'Campus Externo'
];

export const INITIAL_EQUIPMENTS: Equipment[] = [
  {
    id: 'eq-ap-01',
    code: 'AP-01',
    name: 'Access Point Wi-Fi 6 Cisco Catalyst 9115AX',
    location: 'Sala de Cómputo Bachillerato 1',
    brand: 'Cisco',
    model: 'C9115AXI-A',
    serial: 'FOC241923K4',
    parts: ['Fuente de alimentación PoE', 'Antenas omnidireccionales', 'Puerto RJ-45 Gigabit', 'Chasis de disipación'],
    maintenanceTasks: [
      'Limpieza externa y remoción de polvo en rendijas de ventilación',
      'Inspección del cableado estructurado Cat6A y conector RJ45',
      'Verificación de potencia de transmisión y canal de radio',
      'Actualización/comprobación de firmware en Cisco DNA Spaces',
      'Prueba de velocidad y cobertura con analizador de espectro'
    ],
    frequency: 'trimestral',
    status: 'activo',
    observations: 'Equipo crítico para exámenes virtuales Cambridge y pruebas Saber 11.',
    createdAt: '2025-01-10T08:00:00.000Z',
    updatedAt: '2025-01-10T08:00:00.000Z',
  },
  {
    id: 'eq-sw-01',
    code: 'SW-01',
    name: 'Switch Core Capa 3 Cisco Catalyst 3850 48P PoE+',
    location: 'Data Center Principal - Rack A1',
    brand: 'Cisco',
    model: 'WS-C3850-48P-L',
    serial: 'FCW1948B03L',
    parts: ['Fuentes redundantes duales 1100W', 'Módulo de 4 ventiladores extractores', 'Módulo uplink 10G SFP+', 'Tarjeta de apilamiento StackWise-480'],
    maintenanceTasks: [
      'Aspirado de tolvas y limpieza profunda de ventiladores',
      'Inspección termográfica de fuentes de alimentación PoE',
      'Revisión de logs del sistema y errores CRC en puertos troncales',
      'Respaldo de la configuración Running-Config a servidor TFTP',
      'Prueba de conmutación por falla de fuente redundante'
    ],
    frequency: 'semestral',
    status: 'activo',
    observations: 'Columna vertebral de la red de todo el campus escolar.',
    createdAt: '2025-01-12T09:30:00.000Z',
    updatedAt: '2025-01-12T09:30:00.000Z',
  },
  {
    id: 'eq-pc-01',
    code: 'PC-01',
    name: 'Estación de Trabajo Servidor de Dominio / Active Directory',
    location: 'Oficina de Sistemas y Tecnología',
    brand: 'Dell',
    model: 'OptiPlex 7090 Tower',
    serial: '8GK3TX2',
    parts: ['Procesador Intel Core i7-11700', '32GB RAM DDR4 Kingston', 'Arreglo RAID 1 NVMe 1TB', 'Fuente de poder 80 Plus Gold 500W'],
    maintenanceTasks: [
      'Limpieza física interna, lubricación de ventiladores y cambio de pasta térmica',
      'Verificación del estado de salud SMART de discos SSD NVMe',
      'Limpieza de archivos temporales y optimización de base de datos AD',
      'Comprobación de copia de seguridad local y en nube',
      'Prueba de reinicio controlado y servicios DNS/DHCP'
    ],
    frequency: 'trimestral',
    status: 'activo',
    observations: 'Autentica a todos los docentes, administrativos y estudiantes del colegio.',
    createdAt: '2025-01-15T11:00:00.000Z',
    updatedAt: '2025-01-15T11:00:00.000Z',
  },
  {
    id: 'eq-py-01',
    code: 'PY-01',
    name: 'Proyector Interactivo Láser Epson BrightLink 735Fi',
    location: 'Auditorio Principal San Lucas',
    brand: 'Epson',
    model: 'BrightLink 735Fi',
    serial: 'X79K019482',
    parts: ['Fuente de luz láser', 'Módulo óptico ultra corto', 'Filtro de aire electrostático', 'Sensores táctiles interactivos Finger-touch'],
    maintenanceTasks: [
      'Extracción y soplado del filtro de aire y conducto óptico',
      'Limpieza de lente con solución óptica antiestática',
      'Calibración de los lápices interactivos y alineación de la imagen',
      'Revisión del número de horas del motor láser y temperatura de operación',
      'Ajuste mecánico del soporte de montaje en pared'
    ],
    frequency: 'trimestral',
    status: 'activo',
    observations: 'Utilizado para asambleas de padres, grados y eventos institucionales.',
    createdAt: '2025-01-18T14:20:00.000Z',
    updatedAt: '2025-01-18T14:20:00.000Z',
  },
  {
    id: 'eq-ups-01',
    code: 'UPS-01',
    name: 'Sistema de Energía Ininterrumpida Online APC Smart-UPS RT 10kVA',
    location: 'Data Center Principal - Sala de Respaldo Eléctrico',
    brand: 'APC by Schneider Electric',
    model: 'SRT10KXLI',
    serial: 'AS1934293810',
    parts: ['Banco de 32 baterías 12V 9Ah VRLA', 'Módulo inversor estático', 'Bypass automático y manual', 'Tarjeta de gestión de red SNMP AP9631'],
    maintenanceTasks: [
      'Medición de voltaje individual y resistencia interna por cada celda de batería',
      'Inspección termográfica de bornes de conexión y torque de tornillería',
      'Simulación de corte de energía con transferencia a modo batería bajo carga real',
      'Prueba de sensores de temperatura y humedad ambiental de la sala',
      'Limpieza de ventiladores y revisión de alarmas en el log SNMP'
    ],
    frequency: 'mensual',
    status: 'activo',
    observations: 'Protege servidores de calificaciones, conmutación de red y telefonía IP.',
    createdAt: '2025-01-20T10:00:00.000Z',
    updatedAt: '2025-01-20T10:00:00.000Z',
  },
  {
    id: 'eq-aa-01',
    code: 'AA-01',
    name: 'Unidad de Climatización de Precisión InRow 5TR',
    location: 'Data Center Principal',
    brand: 'Liebert Emerson',
    model: 'CRV-CR020',
    serial: 'EM1840291-C',
    parts: ['Compresor Scroll digital', 'Filtros de aire MERV 11', 'Bomba de drenaje de condensado', 'Ventiladores EC de velocidad variable'],
    maintenanceTasks: [
      'Lavado y desinfección de serpentines evaporador y condensador',
      'Sustitución/lavado de filtros de aire de partículas finas',
      'Medición de presiones de gas refrigerante R-410A y recalentamiento',
      'Verificación y prueba del flotador de la bomba de drenaje de condensado',
      'Calibración de sonda de temperatura y control digital'
    ],
    frequency: 'mensual',
    status: 'activo',
    observations: 'Mantiene temperatura constante a 20°C y 50% humedad en servidores.',
    createdAt: '2025-01-22T08:30:00.000Z',
    updatedAt: '2025-01-22T08:30:00.000Z',
  },
  {
    id: 'eq-sw-02',
    code: 'SW-02',
    name: 'Switch de Distribución Cisco SG350-28P Gigabit PoE',
    location: 'Edificio Primaria - Rack Piso 2',
    brand: 'Cisco',
    model: 'SG350-28P',
    serial: 'DNI2209124A',
    parts: ['Fuente de alimentación integrada', '2 Ventiladores laterales', '24 Puertos 10/100/1000 + 2 SFP'],
    maintenanceTasks: [
      'Soplado de polvo y verificación de giro libre de ventiladores',
      'Revisión física del patch cord y marcado de puertos',
      'Comprobación de consumo de potencia PoE por puerto',
      'Copia de seguridad del archivo de configuración'
    ],
    frequency: 'semestral',
    status: 'activo',
    observations: 'Alimenta las cámaras de seguridad y puntos de acceso del bloque de primaria.',
    createdAt: '2025-02-01T09:00:00.000Z',
    updatedAt: '2025-02-01T09:00:00.000Z',
  },
  {
    id: 'eq-py-02',
    code: 'PY-02',
    name: 'Proyector Multimedia BenQ MX560 (Antiguo)',
    location: 'Depósito General de Tecnología',
    brand: 'BenQ',
    model: 'MX560',
    serial: 'PDD1837482',
    parts: ['Lámpara de mercurio 200W', 'Rueda de color DLP', 'Balasto electrónico'],
    maintenanceTasks: ['Inspección general de componentes'],
    frequency: 'anual',
    status: 'baja',
    observations: 'Equipo dado de baja por fin de vida útil y falla en balasto.',
    createdAt: '2024-03-01T09:00:00.000Z',
    updatedAt: '2024-11-15T10:00:00.000Z',
  },
];

export const INITIAL_LOCATIONS: CampusLocation[] = [
  {
    id: 'loc-dc-01',
    name: 'Data Center Principal',
    building: 'Edificio Administrativo',
    areaType: 'datacenter',
    description: 'Sala de servidores central, control de temperatura de precisión y acceso con tarjeta biométrica.',
    status: 'activa',
    createdAt: '2025-01-01T08:00:00.000Z',
    updatedAt: '2025-01-01T08:00:00.000Z',
  },
  {
    id: 'loc-dc-02',
    name: 'Data Center Principal - Rack A1',
    building: 'Edificio Administrativo',
    areaType: 'datacenter',
    description: 'Rack principal de telecomunicaciones, patch panels y switches de capa 3.',
    status: 'activa',
    createdAt: '2025-01-01T08:00:00.000Z',
    updatedAt: '2025-01-01T08:00:00.000Z',
  },
  {
    id: 'loc-dc-03',
    name: 'Data Center Principal - Sala de Respaldo Eléctrico',
    building: 'Edificio Administrativo',
    areaType: 'infraestructura',
    description: 'Bancos de baterías, UPS online 10kVA y tableros regulados de energía.',
    status: 'activa',
    createdAt: '2025-01-01T08:00:00.000Z',
    updatedAt: '2025-01-01T08:00:00.000Z',
  },
  {
    id: 'loc-bach-01',
    name: 'Sala de Cómputo Bachillerato 1',
    building: 'Bloque Bachillerato',
    areaType: 'laboratorio',
    description: '30 estaciones para estudiantes de secundaria y exámenes virtuales Cambridge.',
    status: 'activa',
    createdAt: '2025-01-02T08:00:00.000Z',
    updatedAt: '2025-01-02T08:00:00.000Z',
  },
  {
    id: 'loc-bach-02',
    name: 'Sala de Cómputo Bachillerato 2',
    building: 'Bloque Bachillerato',
    areaType: 'laboratorio',
    description: 'Laboratorio de robótica, informática avanzada y diseño digital.',
    status: 'activa',
    createdAt: '2025-01-02T08:00:00.000Z',
    updatedAt: '2025-01-02T08:00:00.000Z',
  },
  {
    id: 'loc-prim-01',
    name: 'Laboratorio de Primaria',
    building: 'Bloque Primaria',
    areaType: 'laboratorio',
    description: 'Aulas de tecnología para estudiantes de educación primaria.',
    status: 'activa',
    createdAt: '2025-01-03T08:00:00.000Z',
    updatedAt: '2025-01-03T08:00:00.000Z',
  },
  {
    id: 'loc-prim-02',
    name: 'Edificio Primaria - Rack Piso 2',
    building: 'Bloque Primaria',
    areaType: 'infraestructura',
    description: 'Armario de red para interconexión de cámaras de seguridad y APs de primaria.',
    status: 'activa',
    createdAt: '2025-01-03T08:00:00.000Z',
    updatedAt: '2025-01-03T08:00:00.000Z',
  },
  {
    id: 'loc-aud-01',
    name: 'Auditorio Principal San Lucas',
    building: 'Edificio Central',
    areaType: 'auditorio',
    description: 'Espacio multifuncional para grados, asambleas de padres y eventos institucionales.',
    status: 'activa',
    createdAt: '2025-01-04T08:00:00.000Z',
    updatedAt: '2025-01-04T08:00:00.000Z',
  },
  {
    id: 'loc-adm-01',
    name: 'Oficina de Sistemas y Tecnología',
    building: 'Edificio Administrativo',
    areaType: 'oficina',
    description: 'Taller de soporte técnico, mesa de ayuda y servidores de dominio local.',
    status: 'activa',
    createdAt: '2025-01-05T08:00:00.000Z',
    updatedAt: '2025-01-05T08:00:00.000Z',
  },
  {
    id: 'loc-dep-01',
    name: 'Depósito General de Tecnología',
    building: 'Edificio de Servicios',
    areaType: 'otro',
    description: 'Almacenamiento de equipos dados de baja, repuestos y herramientas.',
    status: 'activa',
    createdAt: '2025-01-05T08:00:00.000Z',
    updatedAt: '2025-01-05T08:00:00.000Z',
  },
  {
    id: 'loc-bib-01',
    name: 'Biblioteca General',
    building: 'Edificio Cultural',
    areaType: 'aula',
    description: 'Área de consulta académica y estaciones de trabajo para investigación.',
    status: 'activa',
    createdAt: '2025-01-06T08:00:00.000Z',
    updatedAt: '2025-01-06T08:00:00.000Z',
  },
  {
    id: 'loc-ext-01',
    name: 'Caseta de Generación y Subestación',
    building: 'Campus Externo',
    areaType: 'infraestructura',
    description: 'Planta eléctrica diésel y sistema de conmutación de energía de emergencia.',
    status: 'activa',
    createdAt: '2025-01-06T08:00:00.000Z',
    updatedAt: '2025-01-06T08:00:00.000Z',
  },
];

export const INITIAL_EXECUTIONS_SEED: MaintenanceExecution[] = [
  {
    id: 'exec_eq-ups-01_2026_1',
    equipmentId: 'eq-ups-01',
    year: 2026,
    month: 1,
    scheduledDate: '2026-01-16',
    isExecuted: true,
    executedDate: '2026-01-16 10:45',
    responsibleName: 'Ing. Carlos Mendoza',
    responsibleRole: 'Líder de Infraestructura y Mantenimiento FCBV',
    signatureDataUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
    completedTasks: [
      'Medición de voltaje individual y resistencia interna por cada celda de batería',
      'Inspección termográfica de bornes de conexión y torque de tornillería',
      'Limpieza de ventiladores y revisión de alarmas en el log SNMP'
    ],
    observations: 'Baterías operando al 98% de capacidad nominal. Sin alarmas en el bus.',
    createdAt: '2026-01-16T10:45:00.000Z',
    updatedAt: '2026-01-16T10:45:00.000Z',
  },
  {
    id: 'exec_eq-aa-01_2026_1',
    equipmentId: 'eq-aa-01',
    year: 2026,
    month: 1,
    scheduledDate: '2026-01-23',
    isExecuted: true,
    executedDate: '2026-01-23 15:30',
    responsibleName: 'Téc. Andrés Peña',
    responsibleRole: 'Técnico Especialista Climatización',
    signatureDataUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
    completedTasks: [
      'Lavado y desinfección de serpentines evaporador y condensador',
      'Sustitución/lavado de filtros de aire de partículas finas',
      'Calibración de sonda de temperatura y control digital'
    ],
    observations: 'Filtros reemplazados por repuestos nuevos MERV 11.',
    partsReplaced: ['2x Filtros MERV 11'],
    createdAt: '2026-01-23T15:30:00.000Z',
    updatedAt: '2026-01-23T15:30:00.000Z',
  },
  {
    id: 'exec_eq-ap-01_2026_3',
    equipmentId: 'eq-ap-01',
    year: 2026,
    month: 3,
    scheduledDate: '2026-03-12',
    isExecuted: true,
    executedDate: '2026-03-12 11:15',
    responsibleName: 'Ing. Carlos Mendoza',
    responsibleRole: 'Líder de Infraestructura y Mantenimiento FCBV',
    signatureDataUrl: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==',
    completedTasks: [
      'Limpieza externa y remoción de polvo en rendijas de ventilación',
      'Inspección del cableado estructurado Cat6A y conector RJ45',
      'Verificación de potencia de transmisión y canal de radio',
      'Prueba de velocidad y cobertura con analizador de espectro'
    ],
    observations: 'Firmware verificado versión 17.9.4a. Cobertura óptima.',
    createdAt: '2026-03-12T11:15:00.000Z',
    updatedAt: '2026-03-12T11:15:00.000Z',
  }
];
